name: 'GitHub Build Finish Notification'

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  notify: 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r ".github/send_download_artifact_url/requirements.txt"

      - name: send download artifact page url
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/send_download_artifact_url/send-download-artifact-page-url.py